# Yarn configuration file
# Reference: https://yarnpkg.com/configuration/yarnrc

# Package linker to use (default: node-modules)
nodeLinker: node-modules

# Whether installs should be immutable
enableImmutableInstalls: false

# Enable/disable network requests  
enableNetwork: true

# Default package manager protocol
defaultProtocol: "npm:"

# Enable/disable telemetry
enableTelemetry: false

# Enable/disable progress bars
enableProgressBars: true

# Enable/disable inline builds
enableInlineBuilds: false

# Enable/disable inline hunks
enableInlineHunks: false

# Enable/disable scripts
enableScripts: true

# Enable/disable global cache
enableGlobalCache: true

# Enable/disable mirror
enableMirror: true

# Network timeout (ms)
httpTimeout: 60000

# Compression level (0-9 or mixed)
compressionLevel: mixed

# Enable/disable strict SSL
enableStrictSsl: true

# Preferred architectures
supportedArchitectures:
  os: 
    - linux
    - darwin
    - win32
  cpu: 
    - x64
    - arm64

# Checksums behavior
checksumBehavior: throw

# Enable/disable hardened mode
enableHardenedMode: false

# Enable/disable offline mode
enableOfflineMode: false

# Prefer interactive mode
preferInteractive: false

# Cache migration mode
cacheMigrationMode: always

# Clone concurrency
cloneConcurrency: 2

# Default semver range prefix
defaultSemverRangePrefix: "^"