# This docker-compose.yml file is a part of the arolariu.ro project.

networks:
  arolariu-network:
    external: true

services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    networks:
      - arolariu-network
      - default
    ports:
      - "8080:80"
