import type {IntentId} from "../types";

export const SEED_PHRASES_RO: Record<IntentId, ReadonlyArray<string>> = {
  topSpendingByCategory: [
    "pe ce cheltui cel mai mult luna aceasta",
    "topul categoriilor de cheltuieli luna trecută",
    "unde se duc banii mei",
    "categoria cu cele mai mari cheltuieli anul acesta",
    "ce categorii mă costă cel mai mult",
    "principalele categorii de cheltuieli",
    "ce categorii îmi consumă bugetul",
    "arată-mi categoriile cele mai scumpe",
    "primele 5 categorii de cheltuieli ultimele 3 luni",
    "ce cumpăr cel mai mult pe categorii",
  ],
  topMerchantsByCount: [
    "la ce magazine merg cel mai des",
    "magazinele pe care le vizitez cel mai des",
    "topul magazinelor după număr de vizite luna trecută",
    "unde fac cumpărături cel mai des",
    "magazinele mele cele mai vizitate anul acesta",
    "ce comercianți frecventez",
    "magazinele preferate după vizite",
    "primele 10 magazine cele mai vizitate",
    "magazinele unde fac cumpărături cel mai mult",
    "comercianți frecvenți ultimele 3 luni",
  ],
  topMerchantsBySpend: [
    "unde am cheltuit cel mai mult luna trecută",
    "topul magazinelor după cheltuieli totale",
    "ce magazine mă costă cel mai mult",
    "cele mai mari cheltuieli la un comerciant",
    "magazinele unde cheltui cel mai mult",
    "unde se duc majoritatea banilor mei",
    "primele 5 magazine după cheltuieli totale",
    "ce magazin mi-a luat majoritatea bugetului",
    "comercianții cu cele mai mari cheltuieli",
    "cele mai scumpe magazine anul acesta",
  ],
  totalSpend: [
    "cât am cheltuit luna trecută",
    "totalul cheltuielilor anul acesta",
    "care este totalul meu de cheltuieli",
    "cheltuielile totale pentru alimente luna trecută",
    "cât am cheltuit în ultimele 3 luni",
    "cheltuielile mele totale trimestrul trecut",
    "totalul cheltuielilor din totdeauna",
    "câți bani am cheltuit",
    "costul total al tuturor chitanțelor mele luna trecută",
    "suma cheltuielilor mele luna aceasta",
  ],
  invoiceCount: [
    "câte chitanțe am de luna trecută",
    "numărul de chitanțe anul acesta",
    "câte facturi trimestrul trecut",
    "totalul numărului de chitanțe",
    "numărul de chitanțe în ultimele 3 luni",
    "câte ieșiri la cumpărături am avut luna aceasta",
    "numărul chitanțelor de alimente luna trecută",
    "câte chitanțe în total",
    "numără facturile mele anul acesta",
    "de câte ori am făcut cumpărături săptămâna trecută",
  ],
  topProductsByCount: [
    "ce produse cumpăr cel mai des",
    "articolele cele mai cumpărate anul acesta",
    "articolele pe care le cumpăr cel mai mult",
    "primele 10 produse cele mai frecvente",
    "care este produsul meu cel mai cumpărat luna trecută",
    "articole frecvente în chitanțele mele",
    "produsele pe care le cumpăr des",
    "produse cele mai cumpărate ultimele 3 luni",
    "lucrurile pe care le cumpăr cel mai des",
    "principalele articole recurente",
  ],
  topProductsBySpend: [
    "ce produs mă costă cel mai mult",
    "cea mai mare cheltuială pe un singur articol",
    "primele articole după cheltuieli luna aceasta",
    "produsele cele mai scumpe din chitanțele mele",
    "articolele pe care cheltui cel mai mult",
    "cele mai mari cheltuieli pe produse trimestrul trecut",
    "primele 5 produse după cheltuieli totale",
    "care este cel mai scump articol pe care îl cumpăr",
    "ce produse îmi consumă bugetul",
    "produsele cu cel mai mare cost luna trecută",
  ],
  spendComparison: [
    "cum se compară cheltuielile mele din martie cu aprilie",
    "compară cheltuielile mele luna aceasta cu luna trecută",
    "compararea cheltuielilor martie vs aprilie",
    "compară cheltuielile pentru alimente între luni",
    "cum s-a comparat trimestrul acesta cu trimestrul trecut",
    "diferența de cheltuieli luna trecută vs luna aceasta",
    "compară cheltuielile totale anul trecut și anul acesta",
    "compararea side-by-side a două luni",
    "schimbarea cheltuielilor luna față de luna anterioară",
    "compară cheltuielile mele trimestrul trecut cu trimestrul acesta",
  ],
  averageSpendPerVisit: [
    "care este coșul mediu la alimente",
    "cheltuiala medie per vizită la Lidl",
    "cât cheltui de obicei per ieșire la cumpărături",
    "valoarea medie a chitanței luna aceasta",
    "cheltuiala tipică per vizită",
    "cât în medie pe chitanță",
    "dimensiunea medie a coșului ultimele 6 luni",
    "factura medie la supermarket",
    "cheltuieli medii per ieșire la cumpărături",
    "valoarea tipică a chitanței anul acesta",
  ],
  categoryBreakdown: [
    "defalcarea cheltuielilor pe categorii luna aceasta",
    "în ce categorii am făcut cumpărături săptămâna trecută",
    "arată-mi cheltuielile pe categorii",
    "defalcarea cheltuielilor mele pe categorii",
    "diagramă circulară a cheltuielilor pe categorii",
    "unde se duc banii mei pe categorii",
    "defalcarea cheltuielilor categorie cu categorie",
    "arată-mi cum se împart cheltuielile mele pe categorii",
    "ponderea cheltuielilor per categorie",
    "distribuția cheltuielilor pe categorii",
  ],
};