import type {IntentId} from "../types";

export const SEED_PHRASES_FR: Record<IntentId, ReadonlyArray<string>> = {
  topSpendingByCategory: [
    "sur quoi je dépense le plus ce mois",
    "principales catégories de dépenses le mois dernier",
    "où va mon argent chaque mois",
    "plus grande catégorie de dépenses cette année",
    "quelles catégories me coûtent le plus",
    "mes principales catégories de dépenses",
    "quelles catégories prennent le plus de mon budget",
    "montrez-moi mes plus grands postes de dépense",
    "top 5 des catégories de dépenses des 3 derniers mois",
    "qu'est-ce que j'achète le plus par catégorie",
  ],
  topMerchantsByCount: [
    "chez quels marchands je fais le plus de courses",
    "magasins que je visite le plus souvent",
    "top des magasins par nombre de visites le mois dernier",
    "où je fais le plus souvent mes courses",
    "mes magasins les plus visités cette année",
    "quels détaillants je fréquente",
    "magasins préférés par visites",
    "top 10 des marchands les plus visités",
    "magasins où je fais le plus de courses",
    "marchands fréquents les 3 derniers mois",
  ],
  topMerchantsBySpend: [
    "où ai-je dépensé le plus d'argent le mois dernier",
    "top marchands par dépenses totales",
    "quels magasins me coûtent le plus",
    "plus grosse dépense chez un marchand",
    "marchands chez qui je dépense le plus",
    "où va la plupart de mon argent",
    "top 5 magasins par dépenses totales",
    "quel magasin a pris la plus grande part de mon budget",
    "marchands avec les plus grosses dépenses",
    "magasins les plus chers cette année",
  ],
  totalSpend: [
    "combien j'ai dépensé le mois dernier",
    "dépenses totales cette année",
    "quel est mon total de dépenses",
    "dépenses totales en alimentaire le mois dernier",
    "combien j'ai dépensé ces 3 derniers mois",
    "mes dépenses totales le trimestre dernier",
    "dépenses totales depuis toujours",
    "combien d'argent ai-je dépensé",
    "coût total de tous mes reçus le mois dernier",
    "somme de mes dépenses ce mois",
  ],
  invoiceCount: [
    "combien de reçus ai-je du mois dernier",
    "nombre de reçus cette année",
    "combien de factures le trimestre dernier",
    "nombre total de reçus",
    "nombre de reçus ces 3 derniers mois",
    "combien de courses ce mois",
    "nombre de reçus alimentaires le mois dernier",
    "combien de reçus au total",
    "compter mes factures cette année",
    "combien de fois ai-je fait des courses la semaine dernière",
  ],
  topProductsByCount: [
    "quels produits j'achète le plus souvent",
    "articles les plus achetés cette année",
    "articles que j'achète le plus",
    "top 10 des produits les plus fréquents",
    "quel est mon produit le plus acheté le mois dernier",
    "articles fréquents dans mes reçus",
    "produits que j'achète souvent",
    "produits les plus achetés ces 3 derniers mois",
    "choses que j'achète le plus souvent",
    "principaux articles récurrents",
  ],
  topProductsBySpend: [
    "quel produit me coûte le plus",
    "plus grosse dépense pour un seul article",
    "principaux articles par dépenses ce mois",
    "produits les plus chers dans mes reçus",
    "articles sur lesquels je dépense le plus",
    "plus grosses dépenses sur des produits le trimestre dernier",
    "top 5 produits par dépenses totales",
    "quel est l'article le plus cher que j'achète",
    "quels produits dévorent mon budget",
    "produits avec le coût le plus élevé le mois dernier",
  ],
  spendComparison: [
    "comment mes dépenses de mars se comparent à avril",
    "comparer mes dépenses ce mois avec le mois dernier",
    "comparaison des dépenses mars vs avril",
    "comparer les dépenses alimentaires entre mois",
    "comment ce trimestre se compare au trimestre dernier",
    "différence de dépenses mois dernier vs ce mois",
    "comparer mes dépenses totales l'année dernière et cette année",
    "comparaison côte-à-côte de deux mois",
    "évolution des dépenses d'un mois sur l'autre",
    "comparer mes dépenses du trimestre dernier à ce trimestre",
  ],
  averageSpendPerVisit: [
    "quel est mon panier moyen alimentaire",
    "dépense moyenne par visite à Lidl",
    "combien je dépense d'habitude par sortie shopping",
    "montant moyen du reçu ce mois",
    "dépense typique par visite",
    "combien en moyenne par reçu",
    "taille moyenne du panier les 6 derniers mois",
    "facture moyenne au supermarché",
    "dépenses moyennes par sortie shopping",
    "montant typique du reçu cette année",
  ],
  categoryBreakdown: [
    "répartition des dépenses par catégorie ce mois",
    "dans quelles catégories ai-je fait des courses la semaine dernière",
    "montrez-moi les dépenses par catégorie",
    "répartition de mes dépenses par catégorie",
    "graphique en camembert des dépenses par catégorie",
    "où va mon argent par catégorie",
    "répartition catégorie par catégorie des dépenses",
    "montrez-moi comment mes dépenses se répartissent par catégorie",
    "part des dépenses par catégorie",
    "distribution des dépenses par catégorie",
  ],
};