import type {IntentId} from "../types";

/** ~10 canonical phrasings per intent for the embedding classifier. */
export const SEED_PHRASES_EN: Record<IntentId, ReadonlyArray<string>> = {
  topSpendingByCategory: [
    "what do I spend the most on this month",
    "top spending categories last month",
    "where does my money go each month",
    "biggest spending category this year",
    "what categories cost me the most",
    "my top expense categories",
    "which categories take most of my budget",
    "show me my biggest spending areas",
    "top 5 spending categories last 3 months",
    "what do I buy most by category",
  ],
  topMerchantsByCount: [
    "which merchants do I shop at most",
    "stores I visit most often",
    "top shops by visit count last month",
    "where do I shop most frequently",
    "my most-visited stores this year",
    "which retailers do I go to often",
    "favorite shops by visit count",
    "top 10 most visited merchants",
    "stores I shop at the most",
    "frequent merchants in the past 3 months",
  ],
  topMerchantsBySpend: [
    "where did I spend the most money last month",
    "top merchants by total spend",
    "which stores cost me the most",
    "biggest spend at any merchant",
    "merchants I spend the most at",
    "where does most of my money go",
    "top 5 stores by total spending",
    "which shop took most of my budget",
    "biggest expense merchants",
    "most expensive shops this year",
  ],
  totalSpend: [
    "how much did I spend last month",
    "total spending this year",
    "what's my total spend",
    "total grocery spending last month",
    "how much have I spent in the past 3 months",
    "my total expenses last quarter",
    "all-time total spend",
    "how much money have I spent",
    "total cost of all my receipts last month",
    "sum of my spending this month",
  ],
  invoiceCount: [
    "how many receipts do I have from last month",
    "number of receipts this year",
    "how many invoices last quarter",
    "total receipt count",
    "count of receipts in the past 3 months",
    "how many shopping trips this month",
    "number of grocery receipts last month",
    "how many receipts total",
    "count my invoices this year",
    "how many times did I shop last week",
  ],
  topProductsByCount: [
    "what products do I buy most often",
    "most-purchased items this year",
    "items I buy the most",
    "top 10 most frequent products",
    "what's my most-bought product last month",
    "frequent items in my receipts",
    "products I purchase often",
    "most-purchased products in the past 3 months",
    "things I buy most often",
    "top recurring items",
  ],
  topProductsBySpend: [
    "what product costs me the most",
    "biggest single item expense",
    "top spend items this month",
    "most expensive products in my receipts",
    "items I spend the most on",
    "biggest product expenses last quarter",
    "top 5 products by total spend",
    "what's the costliest item I buy",
    "which products eat my budget",
    "highest-cost products last month",
  ],
  spendComparison: [
    "how does my March spending compare to April",
    "compare my spending this month to last month",
    "spend comparison March vs April",
    "compare grocery spending across months",
    "how did this quarter compare to last",
    "spending difference last month vs this month",
    "compare my total spend last year and this year",
    "side-by-side comparison of two months",
    "month over month spending change",
    "compare my spend last quarter to this quarter",
  ],
  averageSpendPerVisit: [
    "what's my average grocery basket",
    "average spend per visit at Lidl",
    "how much do I usually spend per shopping trip",
    "average receipt amount this month",
    "typical spend per visit",
    "how much per receipt on average",
    "mean basket size last 6 months",
    "average bill at the supermarket",
    "average spending per shopping trip",
    "typical receipt amount this year",
  ],
  categoryBreakdown: [
    "spending breakdown by category this month",
    "what categories did I shop in last week",
    "show me category-wise spending",
    "breakdown of my expenses by category",
    "spending pie chart by category",
    "where does my money go by category",
    "category-by-category spend breakdown",
    "show me how my spend splits by category",
    "share of spending per category",
    "spending distribution by category",
  ],
};