using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using AppHost.Aspire;
using Xunit;

namespace AppHost.Tests;

/// <summary>
/// Unit tests for <see cref="TraefikDynamicConfig"/>'s pure I/O behaviour.
///
/// <para>
/// These cover the YAML rendering shape and parent-directory creation. The
/// Aspire event-subscription wiring is exercised by the AppHost integration
/// pass in Task 9 (manual verification via the Aspire dashboard + Traefik
/// dashboard).
/// </para>
/// </summary>
public sealed class TraefikDynamicConfigTests
{
    [Fact]
    public async Task WriteAsync_EmitsExpectedYamlShape_ForStaticRoutesOnly()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), "traefik-test-" + Guid.NewGuid().ToString("N"));
        var targetFile = Path.Combine(tempDir, "dynamic.yml");
        try
        {
            var staticRoutes = new Dictionary<string, (string Scheme, int Port)>
            {
                ["dashboard.aspire.localhost"] = ("http", 18888),
                ["traefik.localhost"] = ("http", 8080),
            };

            var state = new TraefikDynamicConfig.TraefikConfigState(targetFile, staticRoutes);

            await TraefikDynamicConfig.WriteAsync(state, services: EmptyServiceProvider.Instance);

            Assert.True(File.Exists(targetFile), "Target YAML file should be written.");

            var content = await File.ReadAllTextAsync(targetFile);

            // Header comment is present.
            Assert.Contains("# Generated by Aspire AppHost", content, StringComparison.Ordinal);

            // Top-level structure.
            Assert.Contains("http:", content, StringComparison.Ordinal);
            Assert.Contains("  routers:", content, StringComparison.Ordinal);
            Assert.Contains("  services:", content, StringComparison.Ordinal);

            // Router entries: 'dashboard.aspire' becomes 'dashboard-aspire'
            // (dashes replace dots after the .localhost suffix is stripped).
            Assert.Contains("    dashboard-aspire:", content, StringComparison.Ordinal);
            Assert.Contains("rule: \"Host(`dashboard.aspire.localhost`)\"", content, StringComparison.Ordinal);
            Assert.Contains("service: dashboard-aspire-svc", content, StringComparison.Ordinal);
            Assert.Contains("entryPoints: [websecure]", content, StringComparison.Ordinal);

            Assert.Contains("    traefik:", content, StringComparison.Ordinal);
            Assert.Contains("rule: \"Host(`traefik.localhost`)\"", content, StringComparison.Ordinal);

            // Service entries with full URLs through the docker host gateway.
            Assert.Contains("- url: \"http://host.docker.internal:18888\"", content, StringComparison.Ordinal);
            Assert.Contains("- url: \"http://host.docker.internal:8080\"", content, StringComparison.Ordinal);
            Assert.Contains("tls: {}", content, StringComparison.Ordinal);
        }
        finally
        {
            if (Directory.Exists(tempDir))
            {
                Directory.Delete(tempDir, recursive: true);
            }
        }
    }

    [Fact]
    public async Task WriteAsync_CreatesParentDirectoryIfMissing()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), "traefik-test-" + Guid.NewGuid().ToString("N"));
        var nestedDir = Path.Combine(tempDir, "deep", "nested", "config");
        var targetFile = Path.Combine(nestedDir, "dynamic.yml");
        try
        {
            // Parent directory does not yet exist.
            Assert.False(Directory.Exists(nestedDir), "Precondition: nested directory must not exist yet.");

            var staticRoutes = new Dictionary<string, (string Scheme, int Port)>
            {
                ["api.localhost"] = ("http", 5000),
            };
            var state = new TraefikDynamicConfig.TraefikConfigState(targetFile, staticRoutes);

            await TraefikDynamicConfig.WriteAsync(state, services: EmptyServiceProvider.Instance);

            Assert.True(Directory.Exists(nestedDir), "Nested directory should have been created.");
            Assert.True(File.Exists(targetFile), "Target file should exist after WriteAsync.");
        }
        finally
        {
            if (Directory.Exists(tempDir))
            {
                Directory.Delete(tempDir, recursive: true);
            }
        }
    }

    [Fact]
    public void RenderYaml_IsDeterministic_AndSortsRoutersAlphabetically()
    {
        var staticRoutes = new Dictionary<string, (string Scheme, int Port)>
        {
            ["zeta.localhost"] = ("http", 9000),
            ["alpha.localhost"] = ("http", 1000),
            ["mid.localhost"] = ("http", 5000),
        };
        var state = new TraefikDynamicConfig.TraefikConfigState(
            targetFile: "ignored.yml",
            staticRoutes);

        var yaml = state.RenderYaml();

        // Routers should be in alphabetical order: alpha, mid, zeta.
        var alphaIdx = yaml.IndexOf("    alpha:", StringComparison.Ordinal);
        var midIdx = yaml.IndexOf("    mid:", StringComparison.Ordinal);
        var zetaIdx = yaml.IndexOf("    zeta:", StringComparison.Ordinal);

        Assert.True(alphaIdx >= 0, "alpha router missing");
        Assert.True(midIdx >= 0, "mid router missing");
        Assert.True(zetaIdx >= 0, "zeta router missing");
        Assert.True(alphaIdx < midIdx, "alpha should appear before mid");
        Assert.True(midIdx < zetaIdx, "mid should appear before zeta");

        // Rendering twice yields the same output (no per-call non-determinism).
        Assert.Equal(yaml, state.RenderYaml());
    }

    private sealed class EmptyServiceProvider : IServiceProvider
    {
        public static readonly EmptyServiceProvider Instance = new();
        public object? GetService(Type serviceType) => null;
    }
}
