/**
 * @fileoverview Internal API route for sending emails via Resend.
 * @module app/api/email/route
 *
 * @remarks
 * This route is protected by server-signed internal JWT token (generated by
 * our server actions). The JWT ensures that only our own server actions can
 * call this route—arbitrary client requests cannot forge the internal token.
 *
 * **Why no Clerk auth()?** Server actions call this via fetch(), which doesn't
 * forward cookies. JWT verification alone is sufficient security since only
 * our server actions can generate valid JWTs with the secret.
 *
 * **Architecture**: By moving email sending to an API route, we avoid importing
 * `@react-email/render` in server actions, which was causing peer dependency
 * issues that blocked other server actions from working correctly.
 *
 * @see {@link sendInvoiceShareEmail} for the server action that calls this route
 * @see {@link InvoiceHasBeenSharedWithEmail} for the React Email template
 */

import InvoiceHasBeenSharedWithEmail from "@/../emails/invoices/InvoiceHasBeenSharedWithEmail";
import {addSpanEvent, logWithTrace, withSpan} from "@/instrumentation.server";
import {fetchApiJwtSecret, fetchResendApiKey} from "@/lib/config/configProxy";
import {verifyJwtToken} from "@/lib/utils.server";
import {type NextRequest, NextResponse} from "next/server";
import {Resend} from "resend";

/**
 * Request body structure for the email API.
 */
type EmailRequestBody = Readonly<{
  /** Recipient email address */
  readonly toEmail: string;
  /** Recipient display name */
  readonly toName: string;
  /** Sender display name */
  readonly fromName: string;
  /** Invoice ID being shared */
  readonly invoiceId: string;
}>;

/**
 * POST /api/email - Send invoice share notification email
 *
 * @param request - Next.js request object
 * @returns JSON response with success status
 *
 * @remarks
 * **Security Flow**:
 * 1. Extract and verify internal JWT from Authorization header
 * 2. Validate request body contains required fields
 * 3. Fetch Resend API key from config proxy
 * 4. Send email using React Email template via Resend
 *
 * **Error Handling**:
 * - 403: Missing or invalid internal JWT
 * - 400: Missing required fields in request body
 * - 500: Resend API error or email service not configured
 *
 * @example
 * ```typescript
 * // Called by server action with internal JWT
 * const response = await fetch("/api/email", {
 *   method: "POST",
 *   headers: {
 *     "Content-Type": "application/json",
 *     "Authorization": `Bearer ${internalToken}`,
 *   },
 *   body: JSON.stringify({
 *     toEmail: "user@example.com",
 *     toName: "John",
 *     fromName: "Jane Doe",
 *     invoiceId: "550e8400-e29b-41d4-a716-446655440000",
 *   }),
 * });
 * ```
 */
export async function POST(request: NextRequest): Promise<NextResponse> {
  return withSpan("api.email.send", async () => {
    try {
      // 1. Verify internal JWT token (only our server action can generate this)
      addSpanEvent("auth.jwt.verify");
      const authHeader = request.headers.get("Authorization");
      const token = authHeader?.replace("Bearer ", "");
      if (!token) {
        logWithTrace("warn", "Email API request missing internal token", {}, "api");
        return NextResponse.json({success: false, error: "Missing internal token"}, {status: 403});
      }

      const jwtSecret = await fetchApiJwtSecret();
      const verification = await verifyJwtToken(token, jwtSecret);
      if (!verification.valid) {
        logWithTrace("warn", "Email API request with invalid internal token", {}, "api");
        return NextResponse.json({success: false, error: "Invalid internal token"}, {status: 403});
      }

      addSpanEvent("auth.jwt.verified");

      // 2. Parse and validate request body
      addSpanEvent("request.body.parse");
      const body = (await request.json()) as EmailRequestBody;
      const {toEmail, toName, fromName, invoiceId} = body;

      if (!toEmail || !invoiceId) {
        logWithTrace("warn", "Email API request missing required fields", {toEmail, invoiceId}, "api");
        return NextResponse.json({success: false, error: "Missing required fields: toEmail and invoiceId"}, {status: 400});
      }

      addSpanEvent("request.body.validated", {toEmail, invoiceId});

      // 3. Get Resend API key
      addSpanEvent("resend.api_key.fetch");
      const apiKey = await fetchResendApiKey();
      if (!apiKey) {
        logWithTrace("error", "Resend API key not configured", {}, "api");
        return NextResponse.json({success: false, error: "Email service not configured"}, {status: 500});
      }

      addSpanEvent("resend.api_key.fetched");

      // 4. Send email with React Email template
      addSpanEvent("email.sending", {toEmail, fromName, invoiceId});
      const resend = new Resend(apiKey);

      // Use `react:` prop — Resend's recommended way for API routes
      // This avoids manual pre-rendering and peer dependency issues
      const emailData = await resend.emails.send({
        from: "AROLARIU.RO <doNotReply@mail.arolariu.ro>",
        to: toEmail,
        subject: `${fromName} shared an invoice with you`,
        react: InvoiceHasBeenSharedWithEmail({
          fromUsername: fromName,
          toUsername: toName || toEmail.split("@")[0] || "there",
          identifier: invoiceId,
        }),
      });

      if (emailData.error) {
        console.error("Resend API error:", emailData.error);
        logWithTrace(
          "error",
          "Resend API error",
          {
            error: emailData.error.message ?? "Unknown error",
            errorName: emailData.error.name,
            toEmail,
          },
          "api",
        );
        return NextResponse.json(
          {success: false, error: `Failed to send email: ${emailData.error.message ?? "Unknown error"}`},
          {status: 500},
        );
      }

      addSpanEvent("email.sent", {resendId: emailData.data?.id ?? "unknown"});
      logWithTrace("info", "Invoice share email sent via API route", {toEmail, invoiceId, resendId: emailData.data?.id}, "api");

      return NextResponse.json({success: true});
    } catch (error) {
      const msg = error instanceof Error ? error.message : "Unknown error";
      console.error("Email API route failed:", msg, error);
      logWithTrace("error", "Email route exception", {error: msg}, "api");
      return NextResponse.json({success: false, error: `Internal error: ${msg}`}, {status: 500});
    }
  });
}
