using System.Globalization;
using System.Text;
using Aspire.Hosting;
using Aspire.Hosting.ApplicationModel;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace AppHost.Aspire;

/// <summary>
/// Helper that writes Traefik's file-provider dynamic configuration as Aspire
/// resources become ready, then deletes the file on graceful shutdown.
///
/// <para>
/// Native-process backend pattern: Aspire 13.x spawns project/uvicorn/npm
/// processes directly on the host. Traefik (running in a container via
/// AddContainer) reaches them through the Docker host gateway address
/// <c>host.docker.internal</c>. Each ready resource gets a router rule keyed
/// on a hostname (e.g. <c>api.localhost</c>) and a service entry pointing at
/// <c>http://host.docker.internal:&lt;port&gt;</c>.
/// </para>
///
/// <para>
/// Static routes (e.g. the Aspire dashboard) are also emitted on initial
/// startup. Stale YAML from a previous crash is deleted before resources
/// boot; the file is removed again on graceful shutdown via
/// <see cref="IHostedService.StopAsync"/>.
/// </para>
/// </summary>
internal static class TraefikDynamicConfig
{
    private const string GeneratedHeader =
        "# Generated by Aspire AppHost — do not edit by hand";

    /// <summary>
    /// Registers a Traefik dynamic-config writer that emits a YAML file to
    /// <paramref name="targetFile"/> whenever a tracked Aspire resource
    /// becomes ready. Cleans up the file on startup and shutdown.
    /// </summary>
    /// <param name="builder">The Aspire distributed application builder.</param>
    /// <param name="targetFile">Absolute or relative path where the YAML will be written.</param>
    /// <param name="dynamicResources">
    /// Map of <c>hostname → resource builder</c>. The hostname is used as the
    /// Traefik router name and matched via <c>Host(`hostname`)</c>; the
    /// resource's <c>http</c> endpoint port is used as the service target.
    /// </param>
    /// <param name="staticRoutes">
    /// Map of <c>hostname → (scheme, port)</c> for static targets that aren't
    /// Aspire resources (e.g. the Aspire dashboard on the host).
    /// </param>
    /// <returns>The same <paramref name="builder"/> for chaining.</returns>
    public static IDistributedApplicationBuilder AddTraefikDynamicConfig(
        this IDistributedApplicationBuilder builder,
        string targetFile,
        IReadOnlyDictionary<string, IResourceBuilder<IResourceWithEndpoints>> dynamicResources,
        IReadOnlyDictionary<string, (string Scheme, int Port)> staticRoutes)
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentException.ThrowIfNullOrWhiteSpace(targetFile);
        ArgumentNullException.ThrowIfNull(dynamicResources);
        ArgumentNullException.ThrowIfNull(staticRoutes);

        var state = new TraefikConfigState(targetFile, staticRoutes);

        // Delete any stale YAML before we start. If a prior AppHost crashed
        // without StopAsync, Traefik would otherwise route to dead ports.
        DeleteIfExists(targetFile);

        // Per-resource: when a tracked resource becomes ready, record its
        // allocated port and rewrite the YAML so Traefik picks it up.
        builder.Eventing.Subscribe<ResourceReadyEvent>((evt, ct) =>
        {
            foreach (var (hostname, resourceBuilder) in dynamicResources)
            {
                if (!ReferenceEquals(resourceBuilder.Resource, evt.Resource))
                {
                    continue;
                }

                var port = TryGetHttpPort(resourceBuilder);
                if (port is not null)
                {
                    state.SetDynamic(hostname, port.Value);
                    WriteAsync(state, evt.Services).GetAwaiter().GetResult();
                }
                break;
            }

            return Task.CompletedTask;
        });

        // Initial write covers static routes even before any dynamic resource
        // is ready (so the dashboard router exists immediately).
        builder.Eventing.Subscribe<AfterResourcesCreatedEvent>(async (evt, ct) =>
        {
            await WriteAsync(state, evt.Services).ConfigureAwait(false);
        });

        // Cleanup on graceful shutdown.
        builder.Services.AddSingleton<IHostedService>(sp =>
            new TraefikConfigCleanupService(state, sp.GetService<ILogger<TraefikConfigCleanupService>>()));

        return builder;
    }

    internal static async Task WriteAsync(TraefikConfigState state, IServiceProvider services)
    {
        var yaml = state.RenderYaml();
        var dir = Path.GetDirectoryName(Path.GetFullPath(state.TargetFile));
        if (!string.IsNullOrEmpty(dir))
        {
            Directory.CreateDirectory(dir);
        }

        await File.WriteAllTextAsync(state.TargetFile, yaml).ConfigureAwait(false);

        var logger = services.GetService<ILogger<TraefikConfigState>>();
        logger?.LogInformation("Wrote Traefik dynamic config to {Path}", state.TargetFile);
    }

    internal static void DeleteIfExists(string targetFile)
    {
        try
        {
            if (File.Exists(targetFile))
            {
                File.Delete(targetFile);
            }
        }
        catch (IOException)
        {
            // Best-effort cleanup; another process may briefly hold a handle.
        }
    }

    private static int? TryGetHttpPort(IResourceBuilder<IResourceWithEndpoints> resourceBuilder)
    {
        try
        {
            var endpoint = resourceBuilder.Resource.GetEndpoint("http");
            if (endpoint.IsAllocated)
            {
                return endpoint.Port;
            }
        }
        catch (InvalidOperationException)
        {
            // Endpoint not yet allocated or not present; skip.
        }

        return null;
    }

    /// <summary>
    /// Mutable state for the dynamic-config writer. Holds the latest port for
    /// each dynamic route and the immutable static routes; renders the full
    /// YAML on demand.
    /// </summary>
    internal sealed class TraefikConfigState
    {
        private readonly Dictionary<string, int> _dynamic = new(StringComparer.OrdinalIgnoreCase);
        private readonly IReadOnlyDictionary<string, (string Scheme, int Port)> _static;
        private readonly object _gate = new();

        public TraefikConfigState(
            string targetFile,
            IReadOnlyDictionary<string, (string Scheme, int Port)> staticRoutes)
        {
            TargetFile = targetFile;
            _static = staticRoutes;
        }

        public string TargetFile { get; }

        public void SetDynamic(string hostname, int port)
        {
            lock (_gate)
            {
                _dynamic[hostname] = port;
            }
        }

        public string RenderYaml()
        {
            // Snapshot under lock so concurrent ResourceReady events don't tear.
            KeyValuePair<string, int>[] dynamicSnapshot;
            lock (_gate)
            {
                dynamicSnapshot = _dynamic.OrderBy(kv => kv.Key, StringComparer.OrdinalIgnoreCase).ToArray();
            }

            var staticSnapshot = _static
                .OrderBy(kv => kv.Key, StringComparer.OrdinalIgnoreCase)
                .ToArray();

            var sb = new StringBuilder();
            sb.AppendLine(GeneratedHeader);
            sb.AppendLine("http:");
            sb.AppendLine("  routers:");

            foreach (var (hostname, _) in dynamicSnapshot)
            {
                AppendRouter(sb, hostname);
            }
            foreach (var kv in staticSnapshot)
            {
                AppendRouter(sb, kv.Key);
            }

            sb.AppendLine("  services:");
            foreach (var (hostname, port) in dynamicSnapshot)
            {
                AppendService(sb, hostname, "http", "host.docker.internal", port);
            }
            foreach (var kv in staticSnapshot)
            {
                AppendService(sb, kv.Key, kv.Value.Scheme, "host.docker.internal", kv.Value.Port);
            }

            return sb.ToString();
        }

        private static void AppendRouter(StringBuilder sb, string hostname)
        {
            var routerName = RouterNameFor(hostname);
            sb.Append("    ").Append(routerName).AppendLine(":");
            sb.Append("      rule: \"Host(`").Append(hostname).AppendLine("`)\"");
            sb.AppendLine("      tls: {}");
            sb.Append("      service: ").Append(routerName).AppendLine("-svc");
            sb.AppendLine("      entryPoints: [websecure]");
        }

        private static void AppendService(StringBuilder sb, string hostname, string scheme, string host, int port)
        {
            var routerName = RouterNameFor(hostname);
            sb.Append("    ").Append(routerName).AppendLine("-svc:");
            sb.AppendLine("      loadBalancer:");
            sb.AppendLine("        servers:");
            sb.Append("          - url: \"")
              .Append(scheme).Append("://").Append(host).Append(':')
              .Append(port.ToString(CultureInfo.InvariantCulture))
              .AppendLine("\"");
        }

        /// <summary>
        /// Derives a stable router name from a hostname. <c>api.localhost</c> →
        /// <c>api</c>; <c>dashboard.aspire.localhost</c> → <c>dashboard-aspire</c>.
        /// Falls back to the full hostname (sanitized) when no dot is present.
        /// </summary>
        private static string RouterNameFor(string hostname)
        {
            var trimmed = hostname.EndsWith(".localhost", StringComparison.OrdinalIgnoreCase)
                ? hostname[..^".localhost".Length]
                : hostname;

            // Replace dots with dashes so it's a valid Traefik resource name.
            return trimmed.Replace('.', '-');
        }
    }

    private sealed class TraefikConfigCleanupService : IHostedService
    {
        private readonly TraefikConfigState _state;
        private readonly ILogger<TraefikConfigCleanupService>? _logger;

        public TraefikConfigCleanupService(
            TraefikConfigState state,
            ILogger<TraefikConfigCleanupService>? logger)
        {
            _state = state;
            _logger = logger;
        }

        public Task StartAsync(CancellationToken cancellationToken) => Task.CompletedTask;

        public Task StopAsync(CancellationToken cancellationToken)
        {
            try
            {
                DeleteIfExists(_state.TargetFile);
                _logger?.LogInformation("Removed Traefik dynamic config at {Path}", _state.TargetFile);
            }
            catch (Exception ex)
            {
                _logger?.LogWarning(ex, "Failed to remove Traefik dynamic config at {Path}", _state.TargetFile);
            }
            return Task.CompletedTask;
        }
    }
}
