# This docker-compose will spin up the following data storage containers:
# - Microsoft SQL Server (MSSQL);
# - Microsoft NoSQL Server (CosmosDB);

name: "arolariu-storage"

volumes:
  storage:

networks:
  arolariu-network:
    external: true

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: "mssql"
    environment:
      MSSQL_SA_PASSWORD: "P@ssw0rd1234!"
      ACCEPT_EULA: "Y"
    healthcheck:
      test:
        ["CMD", "sqlcmd", "-U", "sa", "-P", "P@ssw0rd1234!", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 2
    restart: "unless-stopped"
    ports:
      - "8082:1433" # MSSQL default port
    networks:
      - default
      - arolariu-network

  cosmosdb:
    image: "mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest"
    container_name: "cosmosdb"
    ports:
      - "8081:8081" # CosmosDB default port
      # the following ports are used for the data explorer
      - "10250:10250"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
      - "10255:10255"
    volumes:
      - "storage:/var/opt/cosmosdb"
      - "storage:/var/opt/cosmosdb/data"
      - "storage:/var/opt/cosmosdb/logs"
    networks:
      - default
      - arolariu-network
