cacheFolder: "./.yarn/cache"
cacheMigrationMode: "always"
checksumBehavior: "throw"
cloneConcurrency: 2
compressionLevel: 0
enableColors: true
enableConstraintsChecks: true
httpRetry: 3
networkConcurrency: 50
nodeLinker: "node-modules"
tsEnableAutoTypes: true
