# This docker-compose will spin up a Keycloak container:

name: "arolariu-auth"
version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: keycloak
    restart: always
    command: start-dev
    ports:
      - "8080:8080"
    networks:
      - arolariu-network
      - default
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: qazWSXedcRFV1234!
      KC_HOSTNAME_URL: "http://localhost:8080"
      KC_HOSTNAME_ADMIN_URL: "http://localhost:8080"
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
      KC_DB: mssql
      KC_DB_URL: jdbc:sqlserver://mssql:1433;databaseName=arolariu-sql;encrypt=optional;loginTimeout=30;
      KC_DB_USERNAME: sa
      KC_DB_PASSWORD: qazWSXedcRFV1234!
      KC_LOG_LEVEL: INFO
