/**
 * @fileoverview Sidebar definition for the `dotnet-api` content-docs plugin instance.
 *
 * @remarks
 * Uses Docusaurus' `autogenerated` strategy — the sidebar tree is derived
 * from the filesystem layout under the plugin's `path` option. The
 * frontmatter normalizer (`scripts/docs-assemble.normalize.ts`) fills in
 * `sidebar_position` per file so ordering is deterministic without any
 * hand-maintained index.
 */
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  dotnetApiSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
