/**
 * @fileoverview Official taxonomy artifact generator for the monorepo.
 * @module scripts/generate.artifacts
 *
 * @remarks
 * Downloads version-pinned official classification releases, normalizes them into a
 * shared artifact schema, and writes byte-identical minified JSON into both the API
 * and website runtime directories. Generated output is git-ignored and regenerated by
 * local setup, CI, and container builds before compilation.
 */

import {inflateRawSync} from "node:zlib";

/**
 * Extracts a single entry from a ZIP archive by file-name suffix.
 *
 * @remarks
 * Implements just enough of the ZIP specification to locate a central-directory entry
 * and inflate its payload, avoiding a third-party archive dependency.
 *
 * @param zip - Complete ZIP archive bytes.
 * @param suffix - File-name suffix used to select the archive entry.
 * @returns Uncompressed entry bytes.
 * @throws {Error} When the archive is malformed, the entry is absent, or the entry uses
 * a compression method other than stored (0) or deflate (8).
 */
export function extractZipEntry(zip: Uint8Array, suffix: string): Uint8Array {
  const buffer = Buffer.from(zip);
  const eocdSignature = 0x06054b50;
  const centralSignature = 0x02014b50;
  const localSignature = 0x04034b50;

  let eocdOffset = -1;
  for (let offset = buffer.length - 22; offset >= Math.max(0, buffer.length - 65_557); offset--) {
    if (buffer.readUInt32LE(offset) === eocdSignature) {
      eocdOffset = offset;
      break;
    }
  }
  if (eocdOffset < 0) throw new Error("ZIP end-of-central-directory record was not found.");

  const entryCount = buffer.readUInt16LE(eocdOffset + 10);
  let centralOffset = buffer.readUInt32LE(eocdOffset + 16);

  for (let index = 0; index < entryCount; index++) {
    if (buffer.readUInt32LE(centralOffset) !== centralSignature) {
      throw new Error(`Invalid ZIP central directory entry at offset ${centralOffset}.`);
    }

    const compressionMethod = buffer.readUInt16LE(centralOffset + 10);
    const compressedSize = buffer.readUInt32LE(centralOffset + 20);
    const fileNameLength = buffer.readUInt16LE(centralOffset + 28);
    const extraLength = buffer.readUInt16LE(centralOffset + 30);
    const commentLength = buffer.readUInt16LE(centralOffset + 32);
    const localOffset = buffer.readUInt32LE(centralOffset + 42);
    const fileName = buffer.subarray(centralOffset + 46, centralOffset + 46 + fileNameLength).toString("utf8");

    if (fileName.endsWith(suffix)) {
      if (buffer.readUInt32LE(localOffset) !== localSignature) {
        throw new Error(`Invalid ZIP local header for ${fileName}.`);
      }

      const localNameLength = buffer.readUInt16LE(localOffset + 26);
      const localExtraLength = buffer.readUInt16LE(localOffset + 28);
      const dataOffset = localOffset + 30 + localNameLength + localExtraLength;
      const compressed = buffer.subarray(dataOffset, dataOffset + compressedSize);

      if (compressionMethod === 0) return compressed;
      if (compressionMethod === 8) return inflateRawSync(compressed);
      throw new Error(`Unsupported ZIP compression method ${compressionMethod} for ${fileName}.`);
    }

    centralOffset += 46 + fileNameLength + extraLength + commentLength;
  }

  throw new Error(`ZIP entry ending with '${suffix}' was not found.`);
}