/**
 * @fileoverview Official taxonomy artifact generator for the monorepo.
 * @module scripts/generate.artifacts
 *
 * @remarks
 * Downloads version-pinned official classification releases, normalizes them into a
 * shared artifact schema, and writes byte-identical minified JSON into both the API
 * and website runtime directories. Generated output is git-ignored and regenerated by
 * local setup, CI, and container builds before compilation.
 */

import {inflateRawSync} from "node:zlib";
import {mkdir, readFile, writeFile} from "node:fs/promises";
import {resolve} from "node:path";

const GPC_LEVELS: Readonly<Record<number, string>> = {
  1: "segment",
  2: "family",
  3: "class",
  4: "brick",
};

const OUTPUT_ROOTS = [
  resolve("sites/api.arolariu.ro/src/Invoices/Resources/Taxonomies"),
  resolve("sites/arolariu.ro/src/data/taxonomies"),
] as const;

/** @internal */
export const FILE_NAMES = {
  GS1_GPC: "gpc-2026-05.min.json",
} as const satisfies Readonly<Record<ArtifactClassificationSystem, string>>;

/** Classification systems supported by generated artifacts. */
export type ArtifactClassificationSystem = "GS1_GPC";

/** Single normalized taxonomy node. */
export interface TaxonomyArtifactNode {
  readonly code: string;
  readonly officialLabel: string;
  readonly level: string;
  readonly parentCode: string | null;
  readonly hierarchyCodes: readonly string[];
  readonly hierarchyLabels: readonly string[];
  readonly definition: string | null;
  readonly searchText: string;
}

/** Versioned taxonomy artifact consumed by the API and the website. */
export interface TaxonomyArtifact {
  readonly system: ArtifactClassificationSystem;
  readonly version: string;
  readonly sourceUrl: string;
  readonly generatedAt: string;
  readonly attribution: string;
  readonly nodes: readonly TaxonomyArtifactNode[];
}

/** Shape used by the official GS1 GPC JSON document. */
export interface GpcSourceNode {
  readonly Level: number;
  readonly Code: number;
  readonly Title: string;
  readonly Definition: string | null;
  readonly DefinitionExcludes: string | null;
  readonly Active: boolean;
  readonly Childs: readonly GpcSourceNode[];
}

/** Root shape of the official GS1 GPC JSON document. */
export interface GpcSourceDocument {
  readonly LanguageCode: string;
  readonly DateUtc: string;
  readonly Schema: readonly GpcSourceNode[];
}

function isRecord(value: unknown): value is Readonly<Record<string, unknown>> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function requireString(record: Readonly<Record<string, unknown>>, key: string, context: string): string {
  const value = record[key];
  if (typeof value !== "string") throw new Error(`${context} ${key} must be a string.`);
  return value;
}

function optionalString(record: Readonly<Record<string, unknown>>, key: string, context: string): string | null {
  const value = record[key];
  if (value === null || value === undefined) return null;
  if (typeof value !== "string") throw new Error(`${context} ${key} must be a string or null.`);
  return value;
}

function requireNumber(record: Readonly<Record<string, unknown>>, key: string, context: string): number {
  const value = record[key];
  if (typeof value !== "number" || !Number.isFinite(value)) throw new Error(`${context} ${key} must be a number.`);
  return value;
}

function requireBoolean(record: Readonly<Record<string, unknown>>, key: string, context: string): boolean {
  const value = record[key];
  if (typeof value !== "boolean") throw new Error(`${context} ${key} must be a boolean.`);
  return value;
}

function parseGpcNode(value: unknown): GpcSourceNode {
  if (!isRecord(value)) throw new Error("GPC node must be an object.");
  const children = value["Childs"];
  if (!Array.isArray(children)) throw new Error("GPC node Childs must be an array.");

  return {
    Level: requireNumber(value, "Level", "GPC node"),
    Code: requireNumber(value, "Code", "GPC node"),
    Title: requireString(value, "Title", "GPC node"),
    Definition: optionalString(value, "Definition", "GPC node"),
    DefinitionExcludes: optionalString(value, "DefinitionExcludes", "GPC node"),
    Active: requireBoolean(value, "Active", "GPC node"),
    Childs: children.map((child: unknown) => parseGpcNode(child)),
  };
}

function normalizeText(...parts: readonly (string | null | undefined)[]): string {
  return parts
    .filter((part): part is string => typeof part === "string" && part.trim().length > 0)
    .map((part) => part.trim().toLowerCase())
    .join(" ")
    .replaceAll(/\s+/gu, " ");
}

/**
 * Parses and validates the official GS1 GPC JSON document.
 *
 * @param value - Untrusted parsed JSON.
 * @returns Strongly typed source document.
 * @throws {Error} When any required field is missing or has the wrong type.
 */
export function parseGpcDocument(value: unknown): GpcSourceDocument {
  if (!isRecord(value)) throw new Error("GPC document must be an object.");
  const schema = value["Schema"];
  if (!Array.isArray(schema)) throw new Error("GPC document Schema must be an array.");

  return {
    LanguageCode: requireString(value, "LanguageCode", "GPC document"),
    DateUtc: requireString(value, "DateUtc", "GPC document"),
    Schema: schema.map((node: unknown) => parseGpcNode(node)),
  };
}

/**
 * Flattens the official hierarchical GPC schema into Segment through Brick nodes.
 *
 * @remarks
 * Inactive nodes and their descendants are excluded. Nodes whose level falls outside
 * 1-4 are omitted from the output but their children are still visited, so deeper
 * classification levels are preserved.
 *
 * @param schema - Official GPC schema nodes.
 * @returns Normalized active nodes for levels 1-4, in document order.
 */
export function flattenGpcSchema(schema: readonly GpcSourceNode[]): readonly TaxonomyArtifactNode[] {
  const nodes: TaxonomyArtifactNode[] = [];

  const visit = (node: GpcSourceNode, ancestors: readonly TaxonomyArtifactNode[]): void => {
    if (!node.Active) return;

    const level = GPC_LEVELS[node.Level];
    const title = node.Title.trim();
    const definition = node.Definition?.trim() ? node.Definition.trim() : null;

    const current: TaxonomyArtifactNode | null =
      level === undefined
        ? null
        : {
            code: String(node.Code),
            officialLabel: title,
            level,
            parentCode: ancestors.at(-1)?.code ?? null,
            hierarchyCodes: [...ancestors.map((ancestor) => ancestor.code), String(node.Code)],
            hierarchyLabels: [...ancestors.map((ancestor) => ancestor.officialLabel), title],
            definition,
            searchText: normalizeText(
              String(node.Code),
              title,
              definition,
              ...ancestors.map((ancestor) => ancestor.officialLabel),
            ),
          };

    if (current !== null) nodes.push(current);
    const nextAncestors = current === null ? ancestors : [...ancestors, current];
    for (const child of node.Childs) visit(child, nextAncestors);
  };

  for (const root of schema) visit(root, []);
  return nodes;
}

/**
 * Resolves a node and rebuilds its full hierarchy by walking parent links.
 *
 * @param nodes - Normalized nodes containing the target and all of its ancestors.
 * @param code - Node code to resolve.
 * @returns The node with a rebuilt hierarchy and recomputed search text.
 * @throws {Error} When the code is absent, a parent reference dangles, or the parent
 * chain contains a cycle.
 */
export function buildHierarchy(nodes: readonly TaxonomyArtifactNode[], code: string): TaxonomyArtifactNode {
  const nodesByCode = new Map(nodes.map((node) => [node.code, node] as const));
  const selected = nodesByCode.get(code);
  if (selected === undefined) throw new Error(`Taxonomy code '${code}' was not found.`);

  const hierarchy: TaxonomyArtifactNode[] = [];
  const visited = new Set<string>();
  let current: TaxonomyArtifactNode | undefined = selected;

  while (current !== undefined) {
    if (visited.has(current.code)) throw new Error(`Taxonomy hierarchy cycle detected at '${current.code}'.`);
    visited.add(current.code);
    hierarchy.unshift(current);

    if (current.parentCode === null) break;
    const parent = nodesByCode.get(current.parentCode);
    if (parent === undefined) {
      throw new Error(`Taxonomy parent '${current.parentCode}' for '${current.code}' was not found.`);
    }
    current = parent;
  }

  return {
    ...selected,
    hierarchyCodes: hierarchy.map((node) => node.code),
    hierarchyLabels: hierarchy.map((node) => node.officialLabel),
    searchText: normalizeText(
      selected.code,
      selected.officialLabel,
      selected.definition,
      ...hierarchy.map((node) => node.officialLabel),
    ),
  };
}


function validateArtifact(artifact: TaxonomyArtifact): void {
  if (artifact.nodes.length === 0) throw new Error(`${artifact.system} artifact contains no taxonomy nodes.`);

  const nodesByCode = new Map<string, TaxonomyArtifactNode>();
  for (const node of artifact.nodes) {
    if (nodesByCode.has(node.code)) throw new Error(`${artifact.system} contains duplicate code '${node.code}'.`);
    nodesByCode.set(node.code, node);
  }

  for (const node of artifact.nodes) {
    if (node.parentCode !== null && !nodesByCode.has(node.parentCode)) {
      throw new Error(`${artifact.system} parent '${node.parentCode}' for '${node.code}' was not found.`);
    }
    if (node.hierarchyCodes.at(-1) !== node.code) {
      throw new Error(`${artifact.system} hierarchy for '${node.code}' does not end with the selected code.`);
    }
    if (node.hierarchyCodes.length !== node.hierarchyLabels.length) {
      throw new Error(`${artifact.system} hierarchy for '${node.code}' has mismatched code and label lengths.`);
    }
  }
}

/**
 * Writes the same minified artifact into each runtime output directory.
 *
 * @remarks
 * The artifact is validated before any write, and every written file is read back and
 * compared so the API and website copies are provably byte-identical.
 *
 * @param fileName - Generated artifact file name.
 * @param artifact - Artifact to validate and write.
 * @param outputRoots - Output roots; defaults to the API and website runtime directories.
 * @returns Absolute paths written, in output-root order.
 * @throws {Error} When validation fails or the mirrored copies differ.
 */
export async function writeMirroredArtifacts(
  fileName: string,
  artifact: TaxonomyArtifact,
  outputRoots: readonly string[] = OUTPUT_ROOTS,
): Promise<readonly string[]> {
  validateArtifact(artifact);
  const contents = JSON.stringify(artifact);
  const paths = outputRoots.map((root) => resolve(root, fileName));

  await Promise.all(
    paths.map(async (path, index) => {
      const root = outputRoots[index];
      if (root === undefined) throw new Error(`Output root for '${path}' was not found.`);
      await mkdir(root, {recursive: true});
      await writeFile(path, contents, "utf8");
    }),
  );

  const writtenContents = await Promise.all(paths.map((path) => readFile(path, "utf8")));
  if (writtenContents.some((value) => value !== contents)) {
    throw new Error(`Mirrored artifact '${fileName}' was not written identically.`);
  }

  return paths;
}

/**
 * Extracts a single entry from a ZIP archive by file-name suffix.
 *
 * @remarks
 * Implements just enough of the ZIP specification to locate a central-directory entry
 * and inflate its payload, avoiding a third-party archive dependency.
 *
 * @param zip - Complete ZIP archive bytes.
 * @param suffix - File-name suffix used to select the archive entry.
 * @returns Uncompressed entry bytes.
 * @throws {Error} When the archive is malformed, the entry is absent, or the entry uses
 * a compression method other than stored (0) or deflate (8).
 */
export function extractZipEntry(zip: Uint8Array, suffix: string): Uint8Array {
  const buffer = Buffer.from(zip);
  const eocdSignature = 0x06054b50;
  const centralSignature = 0x02014b50;
  const localSignature = 0x04034b50;

  let eocdOffset = -1;
  for (let offset = buffer.length - 22; offset >= Math.max(0, buffer.length - 65_557); offset--) {
    if (buffer.readUInt32LE(offset) === eocdSignature) {
      eocdOffset = offset;
      break;
    }
  }
  if (eocdOffset < 0) throw new Error("ZIP end-of-central-directory record was not found.");

  const entryCount = buffer.readUInt16LE(eocdOffset + 10);
  let centralOffset = buffer.readUInt32LE(eocdOffset + 16);

  for (let index = 0; index < entryCount; index++) {
    if (buffer.readUInt32LE(centralOffset) !== centralSignature) {
      throw new Error(`Invalid ZIP central directory entry at offset ${centralOffset}.`);
    }

    const compressionMethod = buffer.readUInt16LE(centralOffset + 10);
    const compressedSize = buffer.readUInt32LE(centralOffset + 20);
    const fileNameLength = buffer.readUInt16LE(centralOffset + 28);
    const extraLength = buffer.readUInt16LE(centralOffset + 30);
    const commentLength = buffer.readUInt16LE(centralOffset + 32);
    const localOffset = buffer.readUInt32LE(centralOffset + 42);
    const fileName = buffer.subarray(centralOffset + 46, centralOffset + 46 + fileNameLength).toString("utf8");

    if (fileName.endsWith(suffix)) {
      if (buffer.readUInt32LE(localOffset) !== localSignature) {
        throw new Error(`Invalid ZIP local header for ${fileName}.`);
      }

      const localNameLength = buffer.readUInt16LE(localOffset + 26);
      const localExtraLength = buffer.readUInt16LE(localOffset + 28);
      const dataOffset = localOffset + 30 + localNameLength + localExtraLength;
      const compressed = buffer.subarray(dataOffset, dataOffset + compressedSize);

      if (compressionMethod === 0) return compressed;
      if (compressionMethod === 8) return inflateRawSync(compressed);
      throw new Error(`Unsupported ZIP compression method ${compressionMethod} for ${fileName}.`);
    }

    centralOffset += 46 + fileNameLength + extraLength + commentLength;
  }

  throw new Error(`ZIP entry ending with '${suffix}' was not found.`);
}
