/**
 * @fileoverview Recipe type definitions for AI-generated cooking suggestions.
 * @module types/invoices/Recipe
 *
 * @remarks
 * This module defines recipe types for cooking suggestions generated from
 * invoice products. Recipes are AI-generated recommendations based on
 * purchased ingredients.
 *
 * **Generation Process:**
 * 1. AI analyzes products in invoice items
 * 2. Matches against recipe database using ingredient compatibility
 * 3. Filters by missing ingredient count
 * 4. Ranks by complexity and user preferences
 *
 * **Use Cases:**
 * - Meal planning from grocery purchases
 * - Reducing food waste by suggesting recipes for perishables
 * - Discovering new recipes based on available ingredients
 *
 * @see {@link Invoice.possibleRecipes} for recipe attachment
 * @see {@link Product} for ingredient source
 */

import type {Product} from "./index.ts";

/**
 * Indicates the difficulty level of preparing a recipe.
 *
 * @remarks
 * Complexity helps users filter recipes matching their cooking skill.
 * The rating considers number of steps, technique requirements, and
 * estimated time commitment.
 *
 * **Level Definitions:**
 * - `Easy` (1): Simple preparation, basic techniques, <30 min
 * - `Normal` (2): Moderate skill, some cooking techniques, 30-60 min
 * - `Hard` (3): Advanced techniques, multiple steps, >60 min
 *
 * **Filtering:**
 * Users can set maximum complexity in preferences to exclude
 * recipes beyond their comfort level.
 *
 * @example
 * ```typescript
 * const recipe: Recipe = {
 *   complexity: RecipeComplexity.Easy,
 *   // ... other properties
 * };
 *
 * // Filter beginner-friendly recipes
 * const easyRecipes = recipes.filter(r => r.complexity <= RecipeComplexity.Easy);
 * ```
 *
 * @see {@link Recipe} for the complete recipe structure
 */
export enum RecipeComplexity {
  /** Unknown complexity */
  Unknown = 0,

  /** Easy complexity */
  Easy = 1,

  /** Normal complexity */
  Normal = 2,

  /** Hard complexity */
  Hard = 3,
}

/**
 * Represents an AI-generated recipe suggestion based on invoice products.
 *
 * @remarks
 * **Domain Concept:**
 * Recipes are read-only suggestions generated by AI analysis of purchased
 * products. They provide meal ideas using ingredients the user already has.
 *
 * **Ingredient Matching:**
 * The `ingredients` array references products from the invoice that
 * match recipe requirements. Products not found on the invoice are
 * listed separately in the UI as "items to buy".
 *
 * **Time Fields:**
 * - `preparationTime`: Active prep work (chopping, measuring)
 * - `cookingTime`: Passive cooking (baking, simmering)
 * - `duration`: Total time = preparationTime + cookingTime
 *
 * **External References:**
 * `referenceForMoreDetails` links to the source recipe (food blog,
 * cooking site) for detailed instructions and photos.
 *
 * @example
 * ```typescript
 * const recipe: Recipe = {
 *   name: "Simple Pasta Carbonara",
 *   description: "Classic Italian pasta with eggs, cheese, and pancetta",
 *   duration: 25,
 *   complexity: RecipeComplexity.Normal,
 *   ingredients: [pastaProduct, eggProduct, cheeseProduct],
 *   instructions: "1. Cook pasta... 2. Fry pancetta... 3. Mix eggs...",
 *   preparationTime: 10,
 *   cookingTime: 15,
 *   referenceForMoreDetails: "https://example.com/carbonara-recipe"
 * };
 *
 * // Calculate total time
 * const totalMinutes = recipe.preparationTime + recipe.cookingTime;
 * ```
 *
 * @see {@link RecipeComplexity} for difficulty levels
 * @see {@link Product} for ingredient structure
 * @see {@link Invoice.possibleRecipes} for invoice attachment
 */
export type Recipe = {
  /** The name of the recipe. */
  name: string;

  /** The description of the recipe. */
  description: string;

  /** The duration of the recipe, in minutes */
  duration: number;

  /** The complexity level of the recipe. */
  complexity: RecipeComplexity;

  /** The list of ingredients for the recipe. */
  ingredients: Product[];

  /** The cooking instructions for the recipe. */
  instructions: string;

  /** The preparation time for the recipe, in minutes */
  preparationTime: number;

  /** The cooking time for the recipe, in minutes */
  cookingTime: number;

  /** A reference for more details about the recipe. */
  referenceForMoreDetails: string;
};

/**
 * DTO payload for creating a custom recipe.
 *
 * @remarks
 * **Partial Fields:**
 * All fields are optional to support draft recipes and
 * incremental population.
 *
 * **User-Created Recipes:**
 * While most recipes are AI-generated, users can create
 * custom recipes linked to their invoice products.
 *
 * **Validation:**
 * - `duration` should equal `preparationTime` + `cookingTime`
 * - `referenceForMoreDetails` must be a valid URL if provided
 *
 * @example
 * ```typescript
 * const payload: CreateRecipeDtoPayload = {
 *   name: "My Family Recipe",
 *   description: "Grandma secret sauce",
 *   complexity: RecipeComplexity.Hard
 * };
 * ```
 *
 * @see {@link Recipe} for the entity structure
 */
export type CreateRecipeDtoPayload = Partial<Recipe>;

/**
 * DTO payload for updating an existing recipe.
 *
 * @remarks
 * **Partial Updates:**
 * Only provided fields are updated. AI-generated recipes
 * are typically read-only, but user-created recipes can be modified.
 *
 * **Use Cases:**
 * - Correcting AI-generated recipe details
 * - Updating cooking times based on user experience
 * - Adding personal notes to instructions
 *
 * @example
 * ```typescript
 * const updatePayload: UpdateRecipeDtoPayload = {
 *   cookingTime: 20,  // Adjusted from experience
 *   instructions: "Updated instructions with my modifications..."
 * };
 * ```
 *
 * @see {@link Recipe} for the entity structure
 */
export type UpdateRecipeDtoPayload = Partial<Recipe>;

/**
 * DTO payload for removing a recipe suggestion.
 *
 * @remarks
 * **Identification:**
 * Recipes are identified by name since they don't have a separate GUID.
 * The name must exactly match (case-sensitive).
 *
 * **Behavior:**
 * - AI-generated recipes: Dismissed for this invoice only
 * - User-created recipes: Permanently deleted
 *
 * **Regeneration:**
 * Dismissed AI recipes can be regenerated by re-running invoice analysis.
 *
 * @example
 * ```typescript
 * const deletePayload: DeleteRecipeDtoPayload = {
 *   name: "Recipe to remove"
 * };
 * ```
 *
 * @see {@link Recipe} for the entity being deleted
 */
export type DeleteRecipeDtoPayload = {
  /** The name of the recipe. */
  readonly name: string;
};
