# This docker compose will spin up the following management containers:
# - Traefik (Reverse Proxy);
# - Network for external use (by other docker-compose files);

name: "arolariu-management"

networks:
  arolariu-network:
    name: "arolariu-network"
    driver: "bridge"
    attachable: true
    internal: false

volumes:
  caddy-data:
  caddy-config:

services:
  caddy:
    image: caddy:2.8.4-alpine
    container_name: caddy
    restart: unless-stopped
    networks:
      - arolariu-network
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # QUIC
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
