# This docker compose will spin up the following management containers:
# - Traefik (Reverse Proxy);
# - Network for external use (by other docker-compose files);

name: "arolariu-management"

networks:
  arolariu-network:
    name: "arolariu-network"
    driver: "bridge"
    attachable: true
    internal: false

services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-v", "http://localhost:50607/health"]
      interval: 3s
      timeout: 1s
      retries: 10
    networks:
      - arolariu-network
    ports:
      - "50607:80"
