// Ambient declarations for style imports. Lets TypeScript accept
// side-effect imports (`import "./globals.scss"`) and CSS-Modules imports
// (`import styles from "./x.module.scss"`) without `@ts-ignore`.

declare module "*.css" {
  const content: Record<string, string>;
  export default content;
}

declare module "*.scss" {
  const content: Record<string, string>;
  export default content;
}

declare module "*.module.css" {
  const classes: Readonly<Record<string, string>>;
  export default classes;
}

declare module "*.module.scss" {
  const classes: Readonly<Record<string, string>>;
  export default classes;
}

// SVG imports (Next.js treats SVGs as static assets)
declare module "*.svg" {
  const content: string;
  export default content;
}

// Specific module declarations for app assets
declare module "@/app/logo.svg" {
  const content: string;
  export default content;
}

// Raw-text imports (e.g., `import csv from "./file.csv?raw"`).
// Supported by Turbopack (Next.js) and Vite (Vitest) out of the box;
// the `?raw` query suffix tells the bundler to embed the file's text
// content as a string literal at build time.
declare module "*?raw" {
  const content: string;
  export default content;
}

// Specific module declaration for exchange rates CSV
declare module "../../../public/data/exchange-rates.csv?raw" {
  const content: string;
  export default content;
}

// Next.js App Router type declarations for PageProps and LayoutProps
// These types are normally generated by Next.js but need explicit declarations for TypeDoc
declare global {
  type PageProps<TRoute extends string = string> = {
    params: Promise<Record<string, string | string[]>>;
    searchParams: Promise<Record<string, string | string[] | undefined>>;
  };

  type LayoutProps<TRoute extends string = string> = {
    children: React.ReactNode;
    params: Promise<Record<string, string | string[]>>;
  };
}

export {};
