name: "cv-official-trigger"

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: ./sites/cv.arolariu.ro

on:
  push:
    branches: ["main"]
    paths: ["sites/cv.arolariu.ro/**"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: 🚀 Building and deploying the CV platform (cv.arolariu.ro)...
    runs-on: ubuntu-latest
    environment:
      name: "cv-resume"
      url: "https://cv.arolariu.ro"
    steps:
      - name: 🛫 Checking out the branch inside the runner environment...
        uses: actions/checkout@v5

      - name: 📦 Installing Node.js...
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: 📦 Installing dependencies...
        run: |
          npm install
          npm run prepare
          npm run build

      - name: "🚀 Deploying CV website..."
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_CV_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./sites/cv.arolariu.ro/"
          api_location: "./sites/cv.arolariu.ro/build/server"
          output_location: "build/static"
