name: "official-cv-trigger"

permissions:
  contents: read

on:
  push:
    branches: ["main"]
    paths:
      - "sites/cv.arolariu.ro/**"
      - ".github/actions/setup-workspace/**"
      - ".github/actions/static-web-app-build-deploy/**"
      - ".github/workflows/official-cv-trigger.yml"
      - ".github/workflows/reusable-static-webapp.yml"

  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment for deployment."
        options:
          - "production"
        default: "production"
        type: choice

jobs:
  deploy:
    name: 🚀 CV static web app
    if: github.repository == 'arolariu/arolariu.ro'
    uses: ./.github/workflows/reusable-static-webapp.yml
    with:
      site-name: "cv"
      working-directory: "sites/cv.arolariu.ro"
      test-command: "npm run test:unit"
      build-command: "npm run prepare && npm run build"
      app-location: "./sites/cv.arolariu.ro/"
      api-location: "./sites/cv.arolariu.ro/build/server"
      output-location: "build/static"
      environment-name: "cv-resume"
      site-url: "https://cv.arolariu.ro"
    secrets:
      SWA_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_CV_TOKEN }}
