name: "website-official-release"

on:
  workflow_run:
    workflows: ["website-official-build"]
    types: ["completed"]
    branches: ["preview"]
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to release to. (e.g. 'development', 'production')"
        options:
          - "development"
          - "production"
        default: "development"
        required: true
        type: choice
      container_name:
        description: "The name of the container to release. (e.g. 'frontend/dev.arolariu', 'frontend/arolariu')"
        options:
          - "frontend/dev.arolariu"
          - "frontend/arolariu"
        default: "frontend/dev.arolariu"
        required: true
        type: choice

permissions:
  id-token: write
  contents: read

jobs:
  release:
    name: 🚀 Release phase (1/1)
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment || 'development'}}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 🔒 Performing auth against Azure Public Cloud...
        uses: Azure/login@v2.1.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 🔒 Performing auth against private Azure Container Registry...
        uses: Azure/docker-login@v2
        with:
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_ADDRESS }}

      - name: ⚓ Releasing docker container to Azure App Service...
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        env:
          PUBLISH_PROFILE: ${{ inputs.environment == 'production' && secrets.AROLARIU_WEB_APP_PUBLISHER_PROFILE || secrets.AROLARIU_WEB_APP_PUBLISHER_PROFILE_DEV}}
          CONTAINER_NAME: ${{inputs.container_name || 'frontend/dev.arolariu'}}
          CONTAINER_TAG: ${{inputs.environment == 'PRODUCTION' && github.sha || 'latest'}}
        with:
          app-name: ${{ inputs.container_name == 'frontend/arolariu' && 'arolariu' || 'dev-arolariu' }}
          slot-name: "production" # This is the slot name for the production environment of the App Service.
          publish-profile: ${{ secrets.AROLARIU_WEB_APP_PUBLISHER_PROFILE }}
          images: "${{ secrets.AZURE_CONTAINER_REGISTRY_ADDRESS }}/${{env.CONTAINER_NAME}}:${{env.CONTAINER_TAG}}"
